### PR TITLE
Fix feature flaws for duplication detection and case sensitivity

### LINKED ISSUE #95: Fix feature flaw pertaining duplication detection and case sensitivity for user input validation
Modify the duplication detection mechanism for `Name` in `Person` and `Title` in `Article` classes to become case-insensitive and to ignore all whitespaces surrounding each word. 

Modify the validation checks for the status provided by the user to be non case-sensitive in the `parseStatus` method of the `ParserUtil` class.

### PR DESCRIPTION
**Pull request by bennyLCK**
* Let's make Name and Title comparisons non case-sensitive and also by ignoring all whitespaces surrounding each word.

* By doing so, we prevent the user from accidentally entering into the app, two Persons or Articles with the same Name or Title as they may have forgotten they had entered such data before.

* Let's make our status field supplied by the user case-insensitive, so that the user does not find it inconvenient when typing in the status of an article.

We will do so by:

* Editing the `parseStatus` method in the `ParserUtil` class to accept all statuses provided by the user without case-sensitivity constraints.

Closes #95

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -49,6 +49,18 @@ public int compareTo(Name other) {
         return this.fullName.compareTo(other.fullName);
     }
 
+    private boolean areSameNames(String[] name, String[] otherName) {
```
Comment (Ko-Khan) [inline src/main/java/seedu/address/model/person/Name.java:52]: Good practice to use helper functions like this.

**Review by Ko-Khan — APPROVED** [review]
LGTM
